name: courtrankrl
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - numpy
    - pandas
    - tqdm
    - torch
    - faiss-cpu
    - pyarrow
    - scikit-learn
    - networkx
    - python-docx
    - striprtf
    - python-dotenv
    - jupyter
    - ipykernel
    - gymnasium
    - matplotlib
    - seaborn
    - beautifulsoup4
    - azure-storage-blob
    - google-generativeai
    - google-genai
    - docling
    - docling-core
    - sentence-transformers
    - transformers
    - accelerate 